#pragma once
//Constants file

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 800

#define FPS_LIMIT 60

#define SPRITE_SIZE 32

#define PLAYER_TEXTURE_PATH "assets/char1_walk.png"
#define PLAYER_ANIM_SPRITE_DOWN { sf::IntRect(0, 0, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(32, 0, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(64, 0, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(96, 0, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(128, 0, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(160, 0, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(192, 0, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(224, 0, SPRITE_SIZE, SPRITE_SIZE)}
#define PLAYER_ANIM_SPRITE_UP { sf::IntRect(0, 32, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(32, 32, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(64, 32, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(96, 32, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(128, 32, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(160, 32, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(192, 32, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(224, 32, SPRITE_SIZE, SPRITE_SIZE)}
#define PLAYER_ANIM_SPRITE_RIGHT { sf::IntRect(0, 64, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(32, 64, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(64, 64, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(96, 64, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(128, 64, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(160, 64, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(192, 64, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(224, 64, SPRITE_SIZE, SPRITE_SIZE)}
#define PLAYER_ANIM_SPRITE_LEFT { sf::IntRect(0, 96, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(32, 96, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(64, 96, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(96, 96, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(128, 96, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(160, 96, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(192, 96, SPRITE_SIZE, SPRITE_SIZE), sf::IntRect(224, 96, SPRITE_SIZE, SPRITE_SIZE)}

#define PLAYER_MOVEMENT_STEP 4
